soong: Forbidden pkg-config again (#24)
* Fixes kernel build failure in Arch Linux due to
  missing header file error even if it exists

Log:
/home/someone5678/android/TheParasiteProject/kernel/sony/sm8550/scripts/dtc/yamltree.c:9:10: fatal error: 'yaml.h' file not found
         ^~~~~~~~

Change-Id: Ief4bdfb1b6cb734633188b1b019bafb450846dbf

Co-authored-by: someone5678 <someone5678@users.noreply.github.com>